# conda env create -f environment.yml
name: b2f
channels:
  - conda-forge
  - defaults
dependencies:
  - pip
  - python=3.8
  - owslib
  # ng
  - beautifulsoup4
  - ckanapi
  - shapely
  - jsonpath-ng
  - click
  - pandas
  - tqdm
  - colander
  - networkx
  - pyyaml
  # tests
  - pytest
  - flake8
